### PR TITLE
Fix kernel panic on Broadwell-E (and MB?). No integrated graphics.

### PR DESCRIPTION
**Pull request by koush**
Confirmed fix on my 6950X. No integrated graphics on this chip.

### CODE REVIEW

**Comment by koush** [comment]
To be honest, the code for this should be reversed. Opt in, not opt out. Otherwise we hit this bug again with next gen CPUs...

**Comment by koush** [comment]
Didn't realize this wasn't the upstream. It's not indicated as a fork on Github, noticed it in the README later.

Here's a possibly better patch.
https://github.com/kozlek/HWSensors/pull/351

**Comment by RehabMan** [comment]
> Didn't realize this wasn't the upstream. It's not indicated as a fork on Github, noticed it in the README later.

That's because it wasn't forked from a github repo originally.  Originally was on assembla (going from memory).

**Comment by RehabMan** [comment]
I think these changes have already been pulled.

**Pull request closed without merging**
